kind: pipeline
metadata:
  name: 0 - Example Pipeline
  description: |-
    this is a multiple line description that

    can be used as docs

    we can also generate doc from this part
spec:
  steps:
    # import a step
    - ../steps/demo.yaml
    # nested pipelines
    - ./child.yaml