name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Run Gosec Security Scanner
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        go get github.com/securego/gosec/cmd/gosec
        gosec ./... --no-fail
    - name: Build
      run: go build -v cmd/yapl.go

    - name: Test
      run: go test -v ./...
